# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09bbb123f5f2beca816764f5f46660cd02c1e00318e94b648751ce13487391ea90516a3aae5ae1eaf7fb2bf4e36379b87cf92be1de302db92fbeedb368c937b3

test:
  secret_key_base: 802c1a5a42b0609fce5b066c0ff435ac92708a45185373126ffa20de1c73aefecf7abbeb1ec4bedf3f065ed29c8d1aacff6ea9dce34a7d3abb0264600d346b53

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
